version: "3.8"
services:
    zookeeper.local:
        container_name: zookeeper.local
        image: confluentinc/cp-zookeeper:6.2.1
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - ms-pdi
        volumes:
            - zk-data:/var/lib/zookeeper/data
            - zk-txn-logs:/var/lib/zookeeper/log

    
    kafka.local:
        container_name: kafka.local
        image: confluentinc/cp-kafka:6.2.1
        restart: on-failure
        depends_on:
            - zookeeper.local
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper.local:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka.local:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            - "9092:9092"
            - "29092:2902"
        networks:
            - ms-pdi
        volumes:
            - kafka-data:/var/lib/kafka/data

    kafka-ui:
        container_name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
            - "8580:8080"
        restart: always
        depends_on:
            - kafka.local
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka.local:29092
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper.local:2181
        networks:
            - ms-pdi

volumes:
    zk-data:
    zk-txn-logs:
    kafka-data:
    kowl-config:
networks:
    ms-pdi:
        external: false
        name: ms-pdi